# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  config.vm.network "public_network", bridge: 'enp3s0'
  config.vm.network "forwarded_port", guest: 8080, host: 8888

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = 1024
    vb.cpus = 2
  end

  # don't run vbguest on start, we need bzip2 first.
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  # disable default synced folder
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.synced_folder "./sync/", "/home/vagrant/sync"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    #ansible.verbose = "vvv"
  end
end
