---
- name: clone repos from phenotips organization
  git:
    accept_hostkey=yes
    repo=git@github.com:phenotips/{{ item }}.git
    dest={{ base_devdir }}/{{ item }}
    clone=yes
    update=yes
  with_items:
    - build-tools
    - phenotips
    - patient-network
    - phenomecentral.org
